run-android:
	. prepare-env.sh .env.$(ENV) .env && . run-packager.sh && sleep 1 && npx react-native run-android
run-ios:
	. prepare-env.sh .env.$(ENV) .env && . run-packager.sh && sleep 1 && npx react-native run-ios
