# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AgreeModal' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    # Add any other subspecs you want to use in your project
  ]
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  # Pods for AgreeModal

  target 'AgreeModal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  end

  target 'AgreeModalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AgreeModal-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgreeModal-tvOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
